FROM registry.access.redhat.com/ubi8/ubi

LABEL maintainer "danclark@redhat.com"

LABEL   summary="Base image for folding at home client" \
        description="Base image for fah clients"

USER root

RUN dnf --setopt tsflags=nodocs -y update \
 && dnf --setopt tsflags=nodocs -y install make compat-openssl10 \
        freeglut mesa-libGLU python2 pygtk2 libcanberra-gtk2 wget \
 && rm -rf /var/cache/yum

ENTRYPOINT ["/bin/bash"]

