FROM registry.access.redhat.com/ubi8/ubi

LABEL maintainer "danclark@redhat.com"

LABEL   Version="7.5.1" \
        Release="1" \
        summary="Folding at home client" \
        description="Folding at home client."

USER root

RUN dnf --setopt tsflags=nodocs -y update \
 && dnf --setopt tsflags=nodocs -y install make compat-openssl10 \
        freeglut mesa-libGLU python2 pygtk2 libcanberra-gtk2 wget \
 && rm -rf /var/cache/yum

ENTRYPOINT ["/bin/bash"]

